export const Permissions = {
	PublicReagentDelete: 'public_reagent:delete',
	PublicReagentRead: 'public_reagent:read',
	PublicReagentWrite: 'public_reagent:write',
	PrivateReagentDelete: 'private_reagent:delete',
	PrivateReagentRead: 'private_reagent:read',
	PrivateReagentWrite: 'private_reagent:write',
	AmountTypesDelete: 'amount_types:delete',
	AmountTypesRead: 'amount_types:read',
	AmountTypesWrite: 'amount_types:write',
	ReagentTypesDelete: 'reagent_types:delete',
	ReagentTypesRead: 'reagent_types:read',
	ReagentTypesWrite: 'reagent_types:write',
	ExtendingDelete: 'extending:delete',
	ExtendingRead: 'extending:read',
	ExtendingWrite: 'extending:write',
	SpendingDelete: 'spending:delete',
	SpendingRead: 'spending:read',
	SpendingWrite: 'spending:write',
	RealmsDelete: 'realm:delete',
	RealmsRead: 'realm:read',
	RealmsWrite: 'realm:write',
	UsersRead: 'users:read',
	UsersWrite: 'users:write',
	RolesDelete: 'roles:delete',
	RolesRead: 'roles:read',
	RolesWrite: 'roles:write',
	PermissionDelete: 'permission:delete',
	PermissionRead: 'permission:read',
	PermissionWrite: 'permission:write',
} as const

export type Permission = (typeof Permissions)[keyof typeof Permissions]
