export const Titles = Object.freeze({
	Type: 'Вид реактива',
	Name: 'Наименование по сопроводительной документации',
	UName: 'Наименование по ИЮПАК',
	Doc: 'НД',
	Purity: 'Степень чистоты',
	DateOfManufacture: 'Дата изготовления',
	Consignment: 'Партия',
	Manufacturer: 'Производитель',
	ShelfLife: 'Срок годности, мес',
	Place: {
		Main: 'Место хранения',
		Closet: 'Шкаф',
		Shelf: 'Полка',
	},
	IncomingControl: {
		Main: 'Входной контроль',
		ReceiptDate: 'Дата поступления',
		Amount: 'Количество',
		Date: 'Дата проведения ВК',
		Protocol: 'Протокол ВК',
		Result: 'Результат ВК',
	},
	Extending: {
		Main: 'Продление срока годности',
		Date: 'Дата',
		Period: 'Период продления, мес',
	},
	SeizureInformation: 'Сведения об изъятии',
	DisposalInformation: 'Сведения об утилизации',
	Comments: 'Комментарии',
	Notes: 'Примечание',
})
