log_level: debug
log_source: false

http:
    port: 9000

postgres:
    db_name: reagents
    host: 127.0.0.1
    # host: pro.sealur.ru
    port: 5436
    # port: 5432
    ssl_mode: disable
    username: postgres
redis:
    host: 192.168.5.159
    port: 6379
    db: 0

# notification:
#     # start_time: 10
#     # interval: 30s

